compute_environment: LOCAL_MACHINE
#distributed_type: MULTI_GPU

#distributed_type: 'NO'

deepspeed_config:
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero_stage: 3
distributed_type: DEEPSPEED

downcast_bf16: 'no'
gpu_ids: '0,1,2'
machine_rank: 0
main_training_function: main
mixed_precision: 'fp16'
num_machines: 1
num_processes: 3
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
